FROM node:boron

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# Install app dependencies
COPY package.json /usr/src/app/
RUN npm install

# Copy app code
COPY . /usr/src/app

# Run
CMD ["npm", "run", "populateDB"]